// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_data_by_id.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteDataByID = `-- name: DeleteDataByID :exec
DELETE FROM testdata
WHERE id = $1
`

func (q *Queries) DeleteDataByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDataByID, id)
	return err
}
