// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_datatable.sql

package database

import (
	"context"
)

const deleteDataTable = `-- name: DeleteDataTable :exec
TRUNCATE TABLE testdata
`

func (q *Queries) DeleteDataTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteDataTable)
	return err
}
