// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_data.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getData = `-- name: GetData :one
SELECT id, created_at, updated_at, dat, username FROM testdata
WHERE id = $1
`

func (q *Queries) GetData(ctx context.Context, id uuid.UUID) (Testdatum, error) {
	row := q.db.QueryRowContext(ctx, getData, id)
	var i Testdatum
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Dat,
		&i.Username,
	)
	return i, err
}
