// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_dataids_by_user.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getDataByUser = `-- name: GetDataByUser :many
SELECT id FROM testdata
WHERE username = $1
`

func (q *Queries) GetDataByUser(ctx context.Context, username string) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getDataByUser, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
