// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_data.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const insertData = `-- name: InsertData :one
INSERT INTO testdata (id, created_at, updated_at, dat, username)
VALUES(
    gen_random_uuid,
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id
`

type InsertDataParams struct {
	Dat      string
	Username string
}

func (q *Queries) InsertData(ctx context.Context, arg InsertDataParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertData, arg.Dat, arg.Username)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
